ignore_colors = [
	[0, 0, 0, 0],
	# [0, 0, 0, 255], # filter all black
]

# unused, just for upstream compatibility
[versions]
"browser" = 0
"python" = 0
"nodejs" = 0

# priority: higher number = higher chance of being placed

[priorities]
"0" = 0
"1" = 1
"2" = 5
"3" = 10

[[structure]]
name = "banner_overlay_w_heart"
file = "images/banner_overlay_with_button.png"
startx = 754
starty = 660
priority = 3

[[structure]]
name = "tagpro"
file = "images/tagpro2.png"
startx = 1728
starty = 1916
priority = 2

[[structure]]
name = "komi"
file = "images/komi.png"
startx = 713
starty = 646
priority = 2

[[structure]]
name = "aunty_donna"
file = "images/aunty-donna.png"
startx = 738
starty = 653
priority = 2

[[structure]]
name = "throwback"
file = "images/throwback.png"
startx = 747
starty = 668
priority = 2

[[structure]]
name = "pxlsspace"
file = "images/pxlsspace.png"
startx = 773
starty = 702
priority = 2

[[structure]]
name = "mustafar_duel"
file = "images/mustafar_duel.png"
startx = 592
starty = 1522
priority = 2

[[structure]]
name = "ccgc"
file = "images/ccgc.png"
startx = 1002
starty = 1882
priority = 2

[[structure]]
name = "thisisfine"
file = "images/thisisfine.png"
startx = 734
starty = 1474
priority = 2

[[structure]]
name = "optifine"
file = "images/optifine.png"
startx = 460
starty = 1562
priority = 2
